name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'fix/*', 'feature/*' ]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      
      - name: Install npm dependencies
        run: npm ci
      
      - name: Build Tauri app
        run: npm run tauri build
      
      - name: Test basic functionality
        run: |
          echo "Build completed successfully for ${{ matrix.platform }}"
          # Could add more specific tests here